version: '3'

services:

  postgres:
    container_name: postgres-db
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "user-info"

  mongo:
    container_name: mongo-db
    image: mongo:4.2.2
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"