server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user_info_service_route
          uri: lb://user-info-service
          predicates:
            - Path=/info/**
          filters:
            - StripPrefix=1

        - id: audit_service_route
          uri: lb://audit-service
          predicates:
            - Path=/audit/**
          filters:
            - StripPrefix=1

        - id: user_photo_storage_service
          uri: lb://user-photo-storage-service
          predicates:
            - Path=/photo/**
          filters:
            - StripPrefix=1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


