server:
  port: ${PORT:8081}

  error:
    include-message: always

spring:
  application:
    name: user-info-service

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/user-info}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

default:
  employee-pagination:
    pageNumber: 0
    pageSize: 5
    sortField: lastName
    sortDir: asc